const errors = {
  generic: 'Something went wrong',
  required: 'This is a required field',
  maxLength: 'Should not exceed %s characters',
  minLength: 'Should be atleast %s characters',
  number: 'Must be a number',
  alpha: 'Must be Alphabets',
  invalidEmail: 'Invalid Email',
  alphanumeric: 'Accepts alphabets and numbers',
  characters: `Accepts only %s character(s)`,
  decimal: 'Number field must have %s digits after decimal or less',
  maxNumber: 'Should not exceed %s',
  minNumber: 'Cannot be less than %s',
  endDate: 'End Date cannot be before Start Date',
  taxRange: 'Tax percentage cannot be more than 100%',
  subTaxValue1: 'Subtax1 cannot be greated than tax',
  subTaxValue2: 'Subtax2 cannot be greated than tax',
  subTax: 'Subtax cannot be greated than tax',
  taxSum: 'Sum of subtax should be equal to tax',
  image: 'This is not of type image',
  url: 'Enter correct url',
  imageRatio: 'The Image doesnt have the required dimension of 4:3',
  sameServeSize: 'Products with same serve size can not be selected',
  positiveInteger: 'The number should be positive',
  isNumber: 'The Number should not be decimal',
  minimum: 'Mininmum cannot be greter than maximum',
  maximum: 'Maximum cannot be less than maximum',
  phone: 'Must be a valid phone number',
  password: 'Must conatin atleast one alphabet, number, and %s character',
  confirmpassword: 'Passwords must match',
  email: 'Must be of type email',
  permissionRequired: 'Atleast one permission needs to be selected',
  subCustomisation: 'There should be atleast 2 Customisation items',
  listItem: 'There must be atleast 2 List items',
};

export default errors;
